[init]
lastAdvice = long
maxSize = 100
persistence = 1

[thresholds]
#down = -0.025
#up = 0.025

[ema]
weight = 10

[macd]
short = 12
long = 26
signal = 9

[rsi]
interval = 14
low = 30
high = 70
persistence = 1
